version: '2'

services:

  # elasticsearch search and analytics engine
  
  elasticsearch: 
    image: elasticsearch:7.6.2
    container_name: elasticsearch-microservice-stock
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
    networks:
      - elasticsearch-kibana
    restart: always

  # Client kibana
  
  kibana:
    image: kibana:7.6.2
    container_name: kibana-microservice-stock
    ports: 
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elasticsearch-kibana
networks:
  elasticsearch-kibana:
    driver: bridge
