camel:
  springboot:
    name: apache-camel-file-stock

server:
  port: 0

in:
  directory: C:\Users\guill\Documents\FormationJavaData\BIG_DATA_PROJET\datasetes
  file:
    fileFilter: .*.[json|JSON]

spring:
  data:
    mongodb:
      uri: mongodb://192.168.99.101:27017,192.168.99.101:27017
      database: apiStock