kafka:
  boot-server: 192.168.99.100:29092 #192.168.99.101:29092
  topic-name: stock-delete-v1
  consumer-group-id: spring-reactive-stock-groupeId
  client-id: spring-reactive-stock
  auto-ofset-rest: earliest
  enable-auto-commit: true
  auto-commit-interval-ms: 5000
  heartbeat-interval-ms: 300

server:
  port: 8082