version: "2"
services:
 mongodb:
  image: mongo:latest
  container_name: "mongodb"
  environment:
   - MONGO_DATA_DIR=/data/db
   - MONGO_LOG_DIR=/dev/null
  # volumes:
   # - C:/Users/guill/Documents/FormationJavaData/Docker/volumes/volumeMongodb:/data/db
  ports:
   - 27017:27017
